[2025-06-10T14:22:40.057+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-10T14:22:40.191+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_to_stg.load_sales_20180509 manual__2025-06-10T14:22:25.358571+00:00 [queued]>
[2025-06-10T14:22:40.324+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_to_stg.load_sales_20180509 manual__2025-06-10T14:22:25.358571+00:00 [queued]>
[2025-06-10T14:22:40.335+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-10T14:22:40.544+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_sales_20180509> on 2025-06-10 14:22:25.358571+00:00
[2025-06-10T14:22:40.577+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_stg', 'load_sales_20180509', 'manual__2025-06-10T14:22:25.358571+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_to_stg.py', '--cfg-path', '/tmp/tmp307ocl47']
[2025-06-10T14:22:40.597+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-10T14:22:40.604+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask load_sales_20180509
[2025-06-10T14:22:40.613+0000] {standard_task_runner.py:72} INFO - Started process 124 to run task
[2025-06-10T14:22:40.855+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_to_stg.load_sales_20180509 manual__2025-06-10T14:22:25.358571+00:00 [running]> on host d2176540d6d9
[2025-06-10T14:22:41.214+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_to_stg' AIRFLOW_CTX_TASK_ID='load_sales_20180509' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T14:22:25.358571+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T14:22:25.358571+00:00'
[2025-06-10T14:22:41.220+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-10T14:22:41.226+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-10T14:22:41.229+0000] {logging_mixin.py:190} INFO - Current task name:load_sales_20180509 state:running start_date:2025-06-10 14:22:40.194500+00:00
[2025-06-10T14:22:41.230+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_to_stg and current dag run status:running
[2025-06-10T14:22:41.239+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-10T14:22:41.257+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 25, in load_csv_to_postgres
    raise FileNotFoundError(f"{file_path} tidak ditemukan.")
FileNotFoundError: /opt/***/INPUT/20180509/20180509.sales tidak ditemukan.
[2025-06-10T14:22:41.329+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-10T14:22:41.344+0000] {logging_mixin.py:190} INFO - Task start:2025-06-10 14:22:40.194500+00:00 end:2025-06-10 14:22:41.318033+00:00 duration:1.123533
[2025-06-10T14:22:41.356+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_sales_20180509> dag:<DAG: data_ingestion_to_stg> dagrun:<DagRun data_ingestion_to_stg @ 2025-06-10 14:22:25.358571+00:00: manual__2025-06-10T14:22:25.358571+00:00, state:running, queued_at: 2025-06-10 14:22:25.383333+00:00. externally triggered: True>
[2025-06-10T14:22:41.361+0000] {logging_mixin.py:190} INFO - Failure caused by /opt/***/INPUT/20180509/20180509.sales tidak ditemukan.
[2025-06-10T14:22:41.363+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_to_stg, task_id=load_sales_20180509, run_id=manual__2025-06-10T14:22:25.358571+00:00, execution_date=20250610T142225, start_date=20250610T142240, end_date=20250610T142241
[2025-06-10T14:22:41.594+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-10T14:22:41.615+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 152 for task load_sales_20180509 (/opt/***/INPUT/20180509/20180509.sales tidak ditemukan.; 124)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 25, in load_csv_to_postgres
    raise FileNotFoundError(f"{file_path} tidak ditemukan.")
FileNotFoundError: /opt/***/INPUT/20180509/20180509.sales tidak ditemukan.
[2025-06-10T14:22:41.699+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-10T14:22:41.730+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
