[2025-06-11T04:02:32.994+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-11T04:02:33.093+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_to_stg.load_products_20180508 manual__2025-06-11T04:02:25.002715+00:00 [queued]>
[2025-06-11T04:02:33.140+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_to_stg.load_products_20180508 manual__2025-06-11T04:02:25.002715+00:00 [queued]>
[2025-06-11T04:02:33.151+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-11T04:02:33.406+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_products_20180508> on 2025-06-11 04:02:25.002715+00:00
[2025-06-11T04:02:33.490+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T04:02:33.535+0000] {standard_task_runner.py:72} INFO - Started process 479 to run task
[2025-06-11T04:02:33.543+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_stg', 'load_products_20180508', 'manual__2025-06-11T04:02:25.002715+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_to_stg.py', '--cfg-path', '/tmp/tmpxazpq8ks']
[2025-06-11T04:02:33.551+0000] {standard_task_runner.py:105} INFO - Job 201: Subtask load_products_20180508
[2025-06-11T04:02:34.002+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_to_stg.load_products_20180508 manual__2025-06-11T04:02:25.002715+00:00 [running]> on host bc5ec7a98490
[2025-06-11T04:02:34.435+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_to_stg' AIRFLOW_CTX_TASK_ID='load_products_20180508' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T04:02:25.002715+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T04:02:25.002715+00:00'
[2025-06-11T04:02:34.446+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-11T04:02:34.456+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-11T04:02:34.461+0000] {logging_mixin.py:190} INFO - Current task name:load_products_20180508 state:running start_date:2025-06-11 04:02:33.107360+00:00
[2025-06-11T04:02:34.474+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_to_stg and current dag run status:running
[2025-06-11T04:02:34.477+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-11T04:02:34.490+0000] {postgres.py:191} INFO - Running copy expert: COPY stg.products FROM STDIN WITH CSV DELIMITER ';' HEADER;, filename: /opt/***/INPUT/20180508/20180508.products.csv
[2025-06-11T04:02:34.538+0000] {base.py:84} INFO - Retrieving connection 'data_warehouse_project'
[2025-06-11T04:02:34.992+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 32, in load_csv_to_postgres
    pg_hook.copy_expert(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 197, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "74,2988"
CONTEXT:  COPY products, line 2, column price: "74,2988"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 38, in load_csv_to_postgres
    raise RuntimeError(f"[ERROR] Gagal load {file_name}: {str(e)}")
RuntimeError: [ERROR] Gagal load 20180508.products.csv: invalid input syntax for type numeric: "74,2988"
CONTEXT:  COPY products, line 2, column price: "74,2988"

[2025-06-11T04:02:35.044+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-11T04:02:35.049+0000] {logging_mixin.py:190} INFO - Task start:2025-06-11 04:02:33.107360+00:00 end:2025-06-11 04:02:35.043436+00:00 duration:1.936076
[2025-06-11T04:02:35.051+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_products_20180508> dag:<DAG: data_ingestion_to_stg> dagrun:<DagRun data_ingestion_to_stg @ 2025-06-11 04:02:25.002715+00:00: manual__2025-06-11T04:02:25.002715+00:00, state:running, queued_at: 2025-06-11 04:02:25.026075+00:00. externally triggered: True>
[2025-06-11T04:02:35.072+0000] {logging_mixin.py:190} INFO - Failure caused by [ERROR] Gagal load 20180508.products.csv: invalid input syntax for type numeric: "74,2988"
CONTEXT:  COPY products, line 2, column price: "74,2988"
[2025-06-11T04:02:35.074+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_to_stg, task_id=load_products_20180508, run_id=manual__2025-06-11T04:02:25.002715+00:00, execution_date=20250611T040225, start_date=20250611T040233, end_date=20250611T040235
[2025-06-11T04:02:35.132+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-11T04:02:35.136+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 201 for task load_products_20180508 ([ERROR] Gagal load 20180508.products.csv: invalid input syntax for type numeric: "74,2988"
CONTEXT:  COPY products, line 2, column price: "74,2988"
; 479)
Traceback (most recent call last):
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 32, in load_csv_to_postgres
    pg_hook.copy_expert(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 197, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "74,2988"
CONTEXT:  COPY products, line 2, column price: "74,2988"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 38, in load_csv_to_postgres
    raise RuntimeError(f"[ERROR] Gagal load {file_name}: {str(e)}")
RuntimeError: [ERROR] Gagal load 20180508.products.csv: invalid input syntax for type numeric: "74,2988"
CONTEXT:  COPY products, line 2, column price: "74,2988"

[2025-06-11T04:02:35.231+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-11T04:02:35.270+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
