[2025-06-10T14:40:23.325+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-10T14:40:23.431+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_to_stg.load_products_20180508 manual__2025-06-10T14:40:13.807451+00:00 [queued]>
[2025-06-10T14:40:23.483+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_to_stg.load_products_20180508 manual__2025-06-10T14:40:13.807451+00:00 [queued]>
[2025-06-10T14:40:23.487+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-10T14:40:23.577+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_products_20180508> on 2025-06-10 14:40:13.807451+00:00
[2025-06-10T14:40:23.595+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-10T14:40:23.603+0000] {standard_task_runner.py:72} INFO - Started process 298 to run task
[2025-06-10T14:40:23.611+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_stg', 'load_products_20180508', 'manual__2025-06-10T14:40:13.807451+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_to_stg.py', '--cfg-path', '/tmp/tmpjqc0v7el']
[2025-06-10T14:40:23.616+0000] {standard_task_runner.py:105} INFO - Job 203: Subtask load_products_20180508
[2025-06-10T14:40:24.029+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_to_stg.load_products_20180508 manual__2025-06-10T14:40:13.807451+00:00 [running]> on host 548b6c6a89dc
[2025-06-10T14:40:24.583+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_to_stg' AIRFLOW_CTX_TASK_ID='load_products_20180508' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T14:40:13.807451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T14:40:13.807451+00:00'
[2025-06-10T14:40:24.590+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-10T14:40:24.592+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-10T14:40:24.593+0000] {logging_mixin.py:190} INFO - Current task name:load_products_20180508 state:running start_date:2025-06-10 14:40:23.438391+00:00
[2025-06-10T14:40:24.599+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_to_stg and current dag run status:running
[2025-06-10T14:40:24.605+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-10T14:40:24.617+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 25, in load_csv_to_postgres
    raise FileNotFoundError(f"{file_path} tidak ditemukan.")
FileNotFoundError: C:/DNA/data-warehouse-project/INPUT/20180508/20180508.products tidak ditemukan.
[2025-06-10T14:40:24.687+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-10T14:40:24.689+0000] {logging_mixin.py:190} INFO - Task start:2025-06-10 14:40:23.438391+00:00 end:2025-06-10 14:40:24.685330+00:00 duration:1.246939
[2025-06-10T14:40:24.691+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_products_20180508> dag:<DAG: data_ingestion_to_stg> dagrun:<DagRun data_ingestion_to_stg @ 2025-06-10 14:40:13.807451+00:00: manual__2025-06-10T14:40:13.807451+00:00, state:running, queued_at: 2025-06-10 14:40:13.829595+00:00. externally triggered: True>
[2025-06-10T14:40:24.703+0000] {logging_mixin.py:190} INFO - Failure caused by C:/DNA/data-warehouse-project/INPUT/20180508/20180508.products tidak ditemukan.
[2025-06-10T14:40:24.706+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_to_stg, task_id=load_products_20180508, run_id=manual__2025-06-10T14:40:13.807451+00:00, execution_date=20250610T144013, start_date=20250610T144023, end_date=20250610T144024
[2025-06-10T14:40:24.752+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-10T14:40:24.753+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 203 for task load_products_20180508 (C:/DNA/data-warehouse-project/INPUT/20180508/20180508.products tidak ditemukan.; 298)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_to_stg.py", line 25, in load_csv_to_postgres
    raise FileNotFoundError(f"{file_path} tidak ditemukan.")
FileNotFoundError: C:/DNA/data-warehouse-project/INPUT/20180508/20180508.products tidak ditemukan.
[2025-06-10T14:40:24.806+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-10T14:40:24.823+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
