[2025-06-11T09:14:36.590+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-11T09:14:36.608+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_to_stg.dim_group.dim_employee manual__2025-06-11T09:14:10.182020+00:00 [queued]>
[2025-06-11T09:14:36.618+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_to_stg.dim_group.dim_employee manual__2025-06-11T09:14:10.182020+00:00 [queued]>
[2025-06-11T09:14:36.619+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-11T09:14:36.633+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): dim_group.dim_employee> on 2025-06-11 09:14:10.182020+00:00
[2025-06-11T09:14:36.642+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=647) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T09:14:36.643+0000] {standard_task_runner.py:72} INFO - Started process 656 to run task
[2025-06-11T09:14:36.644+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_stg', 'dim_group.dim_employee', 'manual__2025-06-11T09:14:10.182020+00:00', '--job-id', '775', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_to_stg.py', '--cfg-path', '/tmp/tmp_qsprvzw']
[2025-06-11T09:14:36.646+0000] {standard_task_runner.py:105} INFO - Job 775: Subtask dim_group.dim_employee
[2025-06-11T09:14:36.694+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_to_stg.dim_group.dim_employee manual__2025-06-11T09:14:10.182020+00:00 [running]> on host 50af1b76beaf
[2025-06-11T09:14:36.787+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_to_stg' AIRFLOW_CTX_TASK_ID='dim_group.dim_employee' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T09:14:10.182020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T09:14:10.182020+00:00'
[2025-06-11T09:14:36.789+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-11T09:14:36.789+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-11T09:14:36.790+0000] {logging_mixin.py:190} INFO - Current task name:dim_group.dim_employee state:running start_date:2025-06-11 09:14:36.609029+00:00
[2025-06-11T09:14:36.790+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_to_stg and current dag run status:running
[2025-06-11T09:14:36.791+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-11T09:14:36.791+0000] {sql.py:266} INFO - Executing: 
TRUNCATE TABLE dm.dim_employee

INSERT INTO dm.dim_employee (
            employee_id, employee_first_name, employee_middle_initial,
            employee_last_name, employee_birth_date, employee_gender,
            employee_city_id, employee_city_name, employee_country_id,
            employee_country_name, employee_country_code, employee_hire_date,
            start_date, end_date
        )
        SELECT 
            e.employeeid,
            e.firstname,
            e.middleinitial,
            e.lastname,
            e.birthdate,
            e.gender,
            e.cityid,
            ci.cityname,
            ci.countryid,
            co.countryname,
            co.countrycode,
            e.hiredate,
            CURRENT_DATE,
            NULL
        FROM stg.employee e
        LEFT JOIN stg.cities ci ON e.cityid = ci.cityid
        LEFT JOIN stg.countries co ON ci.countryid = co.countryid;
[2025-06-11T09:14:36.800+0000] {base.py:84} INFO - Retrieving connection 'data_warehouse_project'
[2025-06-11T09:14:36.812+0000] {base.py:84} INFO - Retrieving connection 'data_warehouse_project'
[2025-06-11T09:14:36.865+0000] {sql.py:509} INFO - Running statement: 
TRUNCATE TABLE dm.dim_employee

INSERT INTO dm.dim_employee (
            employee_id, employee_first_name, employee_middle_initial,
            employee_last_name, employee_birth_date, employee_gender,
            employee_city_id, employee_city_name, employee_country_id,
            employee_country_name, employee_country_code, employee_hire_date,
            start_date, end_date
        )
        SELECT 
            e.employeeid,
            e.firstname,
            e.middleinitial,
            e.lastname,
            e.birthdate,
            e.gender,
            e.cityid,
            ci.cityname,
            ci.countryid,
            co.countryname,
            co.countrycode,
            e.hiredate,
            CURRENT_DATE,
            NULL
        FROM stg.employee e
        LEFT JOIN stg.cities ci ON e.cityid = ci.cityid
        LEFT JOIN stg.countries co ON ci.countryid = co.countryid;, parameters: None
[2025-06-11T09:14:36.870+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "INSERT"
LINE 4: INSERT INTO dm.dim_employee (
        ^

[2025-06-11T09:14:36.884+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-11T09:14:36.885+0000] {logging_mixin.py:190} INFO - Task start:2025-06-11 09:14:36.609029+00:00 end:2025-06-11 09:14:36.883655+00:00 duration:0.274626
[2025-06-11T09:14:36.885+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): dim_group.dim_employee> dag:<DAG: data_ingestion_to_stg> dagrun:<DagRun data_ingestion_to_stg @ 2025-06-11 09:14:10.182020+00:00: manual__2025-06-11T09:14:10.182020+00:00, state:running, queued_at: 2025-06-11 09:14:10.199485+00:00. externally triggered: True>
[2025-06-11T09:14:36.886+0000] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "INSERT"
LINE 4: INSERT INTO dm.dim_employee (
        ^
[2025-06-11T09:14:36.886+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_to_stg, task_id=dim_group.dim_employee, run_id=manual__2025-06-11T09:14:10.182020+00:00, execution_date=20250611T091410, start_date=20250611T091436, end_date=20250611T091436
[2025-06-11T09:14:36.905+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-11T09:14:36.905+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 775 for task dim_group.dim_employee (syntax error at or near "INSERT"
LINE 4: INSERT INTO dm.dim_employee (
        ^
; 656)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "INSERT"
LINE 4: INSERT INTO dm.dim_employee (
        ^

[2025-06-11T09:14:36.941+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-11T09:14:36.970+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-11T09:14:36.973+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
